Scalarization of savings and income shocks
OpenSourceEconomics/dcegm pull request #41
Opened 2023-01-19 14:16 UTC by viktoriakleinschmidt

The function get_child_state_marginal_util_and_exp_max_values now works for single savings and income shocks instead of arrays exogenous_savings_grid and income_shock_draws.

2023-01-19 14:49 UTC, MaxBlesch requested changes
Very nice work so far. Just minor things!

2023-01-19 14:49 UTC, MaxBlesch commented on src/dcegm/solve.py
> +                marginal_utilities[
Maybe just initialize the array with zeros and then add to each entry the calculated weighted marginal_utilities/max_exp_value

2023-01-19 14:49 UTC, MaxBlesch commented on src/dcegm/egm.py
>      child_node_choice_set = get_state_specific_choice_set(
The child specific choice set, the choice_values_child and choice_policies_child are independent of the savings and income shocks. Can we determine them outside of the for loops and then use them as function argument?

2023-01-19 14:49 UTC, MaxBlesch commented on src/dcegm/egm.py
> +    next_period_policy_interp = np.empty((child_node_choice_set.shape[0], 1))
The second dimension of the array is just 1 and therefore not needed. Just use a one dimensional array!

2023-01-19 14:49 UTC, MaxBlesch commented on src/dcegm/egm.py
> +            1,
Same here. Second dimension not needed.

2023-01-24 09:31 UTC, MaxBlesch commented
Before we introduce jax vmap, we want to the user supplied functions to work on dictionaries instead of DataFrames. Also we want to have a check on the params DataFrame if it contains `taste_shock_scale` , `interest_rate` and `discount_factor`. These are all mandatory for now in the code.

2023-04-07 12:48 UTC, MaxBlesch approved these changes

2023-04-07 17:42 UTC, segsell commented on src/dcegm/interpolation.py
> +    return marg_utils, value_final
Why is the second output called ```value_final```?

2023-04-07 17:42 UTC, segsell commented on src/dcegm/interpolation.py
> +    return marg_utility_interp, value_final
Same here. Why is it the final value?

2023-04-09 12:08 UTC, MaxBlesch commented on src/dcegm/interpolation.py
> +    return marg_utility_interp, value_final
Renamed!

2023-04-09 12:08 UTC, MaxBlesch commented on src/dcegm/interpolation.py
> +    return marg_utils, value_final
Rename!

2023-04-10 20:09 UTC, segsell approved these changes
Great PR, good job everyone!!

2023-04-10 20:09 UTC, merged